channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl=5.26.2
  - perl-parallel-forkmanager=2.02
  - python=3.13.5
  - joblib=1.5.1
  - scikit-learn=1.7.0
  - pandas=2.3.0
  - marisa-trie=1.2.1
  - xgboost=3.0.2
